<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Session;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>session.CreateResponse</code>
 */
class CreateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sessid = 1;</code>
     */
    protected $sessid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sessid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sessid = 1;</code>
     * @return string
     */
    public function getSessid()
    {
        return $this->sessid;
    }

    /**
     * Generated from protobuf field <code>string sessid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessid = $var;

        return $this;
    }

}

